### ISSUE TITLE
manual install

### ISSUE THREAD

**Issue by davidak** [puppet-community/puppet-alternatives#28]
sorry for coming with this weird request, but i am on Ubuntu 12.04 and there is only puppet 2.7.11 as newest version and the command `puppet-module` is introduced in 2.7.13 :(

how can i install it manually and will it work with such an old version?

**Comment by adrienthebo** [comment]
You should be able to clone this module into your modulepath and rename the directory to `alternatives`. This module is tested against 2.7.x, so it may work with 2.7.11. However Puppet 2.7.x is EOL, 2.7.11 is vulnerable to numerous CVEs, and Ubuntu 12.04 is also EOL, so you're really in uncharted territory.

**Comment by davidak** [comment]
i have done that already but it don't work:

```
# puppet resource alternatives
Could not run: Could not find type alternatives
```

but it doesn't matter. i invested too much time already so i will configure alternatives manually on the nodes.
